services:
  - type: web
    name: file-manager
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_TYPE
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_AUTH_URI
        sync: false
      - key: GOOGLE_TOKEN_URI
        sync: false
      - key: GOOGLE_AUTH_PROVIDER_CERT_URL
        sync: false
      - key: GOOGLE_CLIENT_CERT_URL
        sync: false
      - key: GOOGLE_UNIVERSE_DOMAIN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false